const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Behaviors.Turret,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Tilemap,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Particles.Acts.SetInitOpacity,
		C3.Plugins.Particles.Exps.InitGrowRate,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Plugins.Text.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.AddCompressorEffect,
		C3.Plugins.Audio.Acts.RemoveEffects,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Sprite: 0},
	{T: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{Player: 0},
	{Anchor: 0},
	{Life_text: 0},
	{Sine: 0},
	{argent: 0},
	{Jumpthru: 0},
	{B_M: 0},
	{Sprite4: 0},
	{B: 0},
	{B_H: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Keyboard: 0},
	{TiledBackground4: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{TiledBackground5: 0},
	{score_Text: 0},
	{LifeMonster: 0},
	{Sprite12: 0},
	{Bullet: 0},
	{Fade: 0},
	{Kunai_Player: 0},
	{Sine2: 0},
	{three_grass: 0},
	{Sprite14: 0},
	{ChatGPTImage23Nov202517_23_: 0},
	{Text_tapHereToPlay: 0},
	{ChatGPTImage23Nov202517_20_: 0},
	{Sprite15: 0},
	{Rotate: 0},
	{Sprite16: 0},
	{Monster_Life: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Particles: 0},
	{Particles2: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Particles3: 0},
	{Zone: 0},
	{Turret: 0},
	{Sprite13: 0},
	{Kunai_Enemi: 0},
	{argent_texte2: 0},
	{Audio: 0},
	{Play: 0},
	{Sprite24: 0},
	{Mouse: 0},
	{Touch: 0},
	{Text: 0},
	{Sprite25: 0},
	{Text2: 0},
	{score_Text2: 0},
	{tuto_text: 0},
	{tuto_text2: 0},
	{Histoire_Text: 0},
	{Histoire_Text2: 0},
	{Sprite26: 0},
	{Moster_Life: 0},
	{E_03: 0},
	{Text_tapHereToPlay2: 0},
	{T_01: 0},
	{T_2: 0},
	{Tilemap: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Text3: 0},
	{IMG: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{TiledBackground6: 0},
	{Sprite32: 0},
	{B_PS: 0},
	{Sprite2: 0},
	{lUMINAUS: 0},
	{lUMINAUS2: 0},
	{Sprite3: 0},
	{score: 0},
	{Argents: 0},
	{life_Monster: 0},
	{Life: 0},
	{Pause: 0},
	{Music: 0},
	{C: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Life_text: class extends self.ITextInstance {},
	argent: class extends self.ISpriteInstance {},
	B_M: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	B: class extends self.ISpriteInstance {},
	B_H: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	score_Text: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Kunai_Player: class extends self.ISpriteInstance {},
	three_grass: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	ChatGPTImage23Nov202517_23_: class extends self.ISpriteInstance {},
	Text_tapHereToPlay: class extends self.ITextInstance {},
	ChatGPTImage23Nov202517_20_: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Zone: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Kunai_Enemi: class extends self.ISpriteInstance {},
	argent_texte2: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	score_Text2: class extends self.ITextInstance {},
	tuto_text: class extends self.ITextInstance {},
	tuto_text2: class extends self.ITextInstance {},
	Histoire_Text: class extends self.ITextInstance {},
	Histoire_Text2: class extends self.ITextInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	E_03: class extends self.ISpriteInstance {},
	Text_tapHereToPlay2: class extends self.ITextInstance {},
	T_01: class extends self.ISpriteInstance {},
	T_2: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	IMG: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	B_PS: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	lUMINAUS: class extends self.ISpriteInstance {},
	lUMINAUS2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}